---
title: "Data Exploration 2"
output: pdf_document
---

```{r setup, include=FALSE}
install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
library(ggplot2)
library(lubridate)
```

```{r}
NorthWestRiverSummary <- whatNWISdata(siteNumbers = "02043410")




NorthWestRiver <- readNWISuv(siteNumbers = "02043410",
                             parameterCd = "00060",
                             startDate = "2006-03-04",
                             endDate = "2007-06-19") 

NorthWestRiver$dateTime <- as.Date(NorthWestRiver$dateTime, "%m/%d/%y")


NorthWestRiver2 <- readNWISdv(siteNumbers = "02043410",
                              parameterCd = "00095",
                              startDate = "",
                              endDate = "")

NorthWestRiverPlot <-
  ggplot(NorthWestRiver, aes(x = dateTime, y = X_00060_00000)) +
  geom_line(alpha = 0.5)
print(NorthWestRiverPlot)

NorthWestRiverPlot2 <-
  ggplot(NorthWestRiver2, aes(x = Date, y = X_00095_00003)) +
  geom_line(alpha = 0.5)
print(NorthWestRiverPlot2)

```



```{r}

TullRiver <- readNWISuv(siteNumbers = "02043415",
                           parameterCd = "00060",
                           startDate = "",
                           endDate = "")

TullRiver2 <- readNWISdv(siteNumbers - "02043415",
                         parameterCd = "00095",
                         startDate = "",
                         endDate = "")

```
